### ISSUE TITLE
package.json is missing

### ISSUE THREAD

**Issue by kyawswa** [thihakyaw/youtube-auto-stream#2]
I cannot run npm install without package.json.

**Comment by thihakyaw** [comment]
I do not know why package.json was not in there but there is package-lock.json to install npm packages. It works well on my other computers. If you got an error when running npm install, please let me see the screenshot.

**Comment by kyawswa** [comment]
% npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/admin/Downloads/youtube-auto-stream-master/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/admin/Downloads/youtube-auto-stream-master/package.json'
npm WARN youtube-auto-stream-master No description
npm WARN youtube-auto-stream-master No repository field.
npm WARN youtube-auto-stream-master No README data
npm WARN youtube-auto-stream-master No license field.

up to date in 0.982s
found 0 vulnerabilities

% npm -v
6.14.15

I didn't found package.json in .gitignore file. it looks ok.

**Comment by kyawswa** [comment]
I found such answer on SOF https://stackoverflow.com/a/53578685 for your reference. Thanks.

**Comment by kaungmyatlwin** [comment]
@thihakyaw  Include `package.json` in the repo. Here's my reconstructed version of your dependencies.

```json
{
  "name": "youtube-auto-stream",
  "version": "1.0.0",
  "description": "Stream YouTube automatically",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/thihakyaw/youtube-auto-stream.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/thihakyaw/youtube-auto-stream/issues"
  },
  "homepage": "https://github.com/thihakyaw/youtube-auto-stream#readme",
  "dependencies": {
    "dotenv": "^10.0.0",
    "puppeteer": "^10.2.0"
  }
}
```

**Comment by thihakyaw** [comment]
added package.json
:D
